###########################
######## ENDPOINTS ########
###########################

#### GET ALL COMMENTS ####
GET http://localhost:8000/comments 

#### GET COMMENT BY ID ####
GET http://localhost:8000/comments/1

#### ADD COMMENT ####
POST http://localhost:8000/comments 
Content-Type: application/json

{
    "comment": "Thanks a lot Sherlock.",
    "answer_id": 3,
    "user_id": 4
}

#### UPDATE COMMENT ####
PUT http://localhost:8000/comments/1
Content-Type: application/json

{
    "comment": "Thanks for the clear and concise answer!",
    "answer_id": 1,
    "user_id": 1
}

#### DELETE COMMENT ####
DELETE http://localhost:8000/comments/6
