###########################
######## ENDPOINTS ########
###########################

#### GET ALL USERS ####
GET http://localhost:8000/users


#### GET ALL USER BY ID ####
GET http://localhost:8000/users/2

#### ADD USER ####
POST http://localhost:8000/users
Content-Type: application/json

{
    "display_name": "olly_steele",
    "email": "oliversteele@hotmail.uk",
    "password": "K!llsw1tch"
}

#### UPDATE USER ####
PUT http://localhost:8000/users/1
Content-Type: application/json

{
    "display_name": "John Donut",
    "email": "johndonut@example.com",
    "password": "password123"
}

#### DELETE USER ####
DELETE http://localhost:8000/users/2
