###########################
######## ENDPOINTS ########
###########################

#### SIGN IN USER ####
### NEW PASSWORD: newPWD2023#
POST http://localhost:8000/auth/sign-in
Content-Type: application/json

{
    "email": "stacknewbie@gmail.com",
    "password": "newPWD2023#" 
}

#### GET ALL USERS ####
GET http://localhost:8000/users

#### GET USER BY ID ####
GET http://localhost:8000/users/3

#### ADD USER ####
POST http://localhost:8000/users
Content-Type: application/json

{
    "display_name": "admin",
    "email": "stacknewbie@gmail.com",
    "password": "MocPeydwimOkBe3"
}

#### UPDATE USER ####
PUT http://localhost:8000/users/6
Content-Type: application/json

{
    "display_name": "Jake Jillan",
    "email": "jakejillan@example.com",
    "password": "jake's password"
}

#### DELETE USER ####
DELETE http://localhost:8000/users/2
