###########################
######## ENDPOINTS ########
###########################

# ADMIN EMAIL : admin@gmail.com
# ADMIN PASSWORD : adminUSER2023@#

# REQUEST RESET PASSWORD REQUEST ENDPOINT: /reset/:email

##### REQUEST FOR PASSWORD RESET | When a user is redirected to this page, 
#       a new token is assigned to them       
#
#                **Password Reset Page**
#
#               Email: __________________
#       
#                 ********************
#                 |   RESET BUTTON   |
#                 ********************
# 
# THE FOLLOWING REQUEST WITH SEND AN EMAIL WITH A RESET LINK

### REQUEST PASSWORD RESET ###
GET http://localhost:4000/reset/jonathanndambuki16@gmail.com

# RESET PASSWORD ENDPOINT : /reset/password/:email

### RESET PASSWORD ###
PUT http://localhost:4000/reset/password/jonathanndambuki16@gmail.com
Content-Type: application/json
TOKEN:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJkaXNwbGF5X25hbWUiOiJhZG1pbiIsImVtYWlsIjoic3RhY2tuZXdiaWVAZ21haWwuY29tIiwiZW1haWxlZCI6MCwiZGVsZXRlZCI6MCwiYWRtaW4iOjAsImlhdCI6MTY4NzM3MTk4OSwiZXhwIjoxNjg3NzMxOTg5fQ.rG77tyxUXD8qm6SSoEOBFGbkUfTNpddzK3V_ne90qHY

{
    "email": "jonathanndambuki16@gmail.com",
    "password": "new_password"
}

### REQUEST PASSWORD RESET ###
GET http://localhost:4000/reset/guitarhonest@gmail.com

### RESET PASSWORD ###
PUT http://localhost:4000/reset/password/guitarhonest@gmail.com
Content-Type: application/json
TOKEN:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2LCJkaXNwbGF5X25hbWUiOiJhZG1pbiIsImVtYWlsIjoic3RhY2tuZXdiaWVAZ21haWwuY29tIiwiZW1haWxlZCI6MCwiZGVsZXRlZCI6MCwiYWRtaW4iOjAsImlhdCI6MTY4NzM3MTk4OSwiZXhwIjoxNjg3NzMxOTg5fQ.rG77tyxUXD8qm6SSoEOBFGbkUfTNpddzK3V_ne90qHY

{
    "email": "guitarhonest@gmail.com",
    "password": "new_password"
}
